### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [Augustoromera/Proyecto-Final-RC-Grupo3-Backend#3]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/Augustoromera/Proyecto-Final-RC-Grupo3-Backend/assets/53904695/ffcb5111-dae8-4afb-ad19-278e880f9179)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Augustoromera** [comment]
Buen dia, gracias por el consejo. fueron quitados todos los comentarios del repositorio [Proyecto-Final-RC-Grupo3-Backend](https://github.com/Augustoromera/Proyecto-Final-RC-Grupo3-Backend)
